In [10]:
# generate an array of zeroes using inbuilt numpy function
import numpy as np

np.zeros(3)

array([0., 0., 0.])

In [11]:
#run the given code and find the dot product of both arrays
a = np.random.randint(2,10,(3,4))
b = np.random.randint(2,10,(4,3))
print(a)
print(b)

[[4 6 3 8]
 [2 4 9 7]
 [2 7 6 8]]
[[5 9 9]
 [8 8 7]
 [3 9 8]
 [7 3 2]]


In [12]:
a.dot(b)

array([[133, 135, 118],
       [118, 152, 132],
       [140, 152, 131]])

In [13]:
b.dot(a)

array([[ 56, 129, 150, 175],
       [ 62, 129, 138, 176],
       [ 46, 110, 138, 151],
       [ 38,  68,  60,  93]])

In [ ]:
# read the csv file provided using pandas and display the first 5 entries

In [14]:
import pandas as pd

In [40]:
#read the csv from drive
data = pd.read_csv('/content/data.csv')

In [41]:
# display the first 5 entries
data.head(5)

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

In [42]:
#decribe the data with all features
data.columns

Index(['OBJECTID', 'UNIT_NAME', 'DESCRIPTION', 'ACRES', 'SHAPE.AREA',
       'SHAPE.LEN'],
      dtype='object')

In [43]:
# find the total count of missing values for each feature
len(data.isnull())

25

In [45]:
# display all the unique values from the 'DESCRIPTION' column
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [48]:
# create a grouped table using 'Description' as the grouping columns with the means of all the other columns
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [49]:
# generate a random sample of 10 rows from the data
data.sample(5)

OBJECTID                              UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
3         24                 Fort Ransom State Park  ...   0.000444   0.128733
16        37             Elkhorn State Natural Area  ...   0.000127   0.067082
18        39        Gunlogson State Nature Preserve  ...   0.000048   0.040465
4         25              Grahams Island State Park  ...   0.000469   0.125546
22        44  Turtle Mountain State Recreation Area  ...   0.000345   0.086487

[5 rows x 6 columns]

In [53]:
# add a feature called 'New_Feature' to the new Dataset and Add random float values in between 0 and 1 using numpy
data['New Feature'] = np.random.random(data.shape[0])

In [54]:
print(data['New Feature'])

0     0.656636
1     0.540504
2     0.741481
3     0.144871
4     0.336068
5     0.891297
6     0.180078
7     0.462590
8     0.108162
9     0.218717
10    0.932994
11    0.282975
12    0.891183
13    0.858372
14    0.454209
15    0.488253
16    0.698479
17    0.593190
18    0.517200
19    0.239961
20    0.132759
21    0.598014
22    0.574794
23    0.235476
24    0.535263
Name: New Feature, dtype: float64


In [59]:
# replace zero value of column 'OBJECTID' with mean value permanently
data.replace(0,data.OBJECTID.mean(),inplace=True)

In [60]:
data.OBJECTID

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64